# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Brett Harris
title: Senior Network System Administrator
email: brett.h@email.co.uk
website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: facespics
github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  나이 : 30 세 (1991년 생)

  최종 학력 : 홍익대학교 졸업

  사는 곳 : 서울특별시 강남구
  
  병역사항 : 군필(2012.01~2013.10)

  사용 기술 : <mark>Java</mark> <mark>Java Script</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
